<div class="t_t3 t_t4 fixed">
    <h4 class="fl fixed">
        <a href="{dede:field.typeurl/}" title="{dede:field.typename/}">
            {dede:field.typename/}</a><em>/&nbsp;&nbsp;features</em></h4>
    <a href="{dede:field.typeurl/}" title="{dede:field.typename/}" class="more fr">
        + 更多</a>
</div>
<ul class="pro_list fixed">
            {dede:arclist row="3"}
            <li><a href="[field:arcurl/]" title="[field:title/]">
                <img class="classname" style="display: inline;" _src="/UploadFiles/Others/20141021V6028V4F68.jpg" src="[field:picname/]"
                    alt="[field:title/]" title="[field:title/]" />
            </a><span><a href="[field:arcurl/]" title="[field:title/]">
                 [field:title/]</a></span>
                <p class="fixed">
                    <a href="[field:arcurl/]" title="[field:title/]">
                        产品详情 >></a><a title="批发咨询" target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=87886663&site=qq&menu=yes">批发咨询
                            >></a></p>
            </li>
			{/dede:arclist}
        
</ul>