<?php
$z[0]=Array("field","",75,96);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",105,127);
$z[1][4]['name']="typename";
$z[2]=Array("field","",143,165);
$z[2][4]['name']="typename";
$z[3]=Array("field","",219,240);
$z[3][4]['name']="typeurl";
$z[4]=Array("field","",249,271);
$z[4][4]['name']="typename";
$z[5]=Array("arclist","\r\n            <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                <img class=\"classname\" style=\"display: inline;\" _src=\"/UploadFiles/Others/20141021V6028V4F68.jpg\" src=\"[field:picname/]\"\r\n                    alt=\"[field:title/]\" title=\"[field:title/]\" />\r\n            </a><span><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                 [field:title/]</a></span>\r\n                <p class=\"fixed\">\r\n                    <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                        产品详情 >></a><a title=\"批发咨询\" target=\"_blank\" href=\"http://wpa.qq.com/msgrd?v=3&uin=87886663&site=qq&menu=yes\">批发咨询\r\n                            >></a></p>\r\n            </li>\r\n			",362,1121);
$z[5][4]['row']="3";

?>