<dl class="news_dl">
                                <dt><a class="dt_1" title="[field:title/]" target="_blank" href="[field:arcurl/]">
                                    [field:title/]</a><span class="dt_2">[
                                        [field:pubdate function="MyDate('Y-m-d',@me)"/]
                                        ]</span></dt>
                                <dd>
                                  [field:info/]</dd>
                            </dl>