<dl class="pd_list_dl">
                            <dt><a target="_blank" href="[field:arcurl/]"
                                title="[field:picname/]">
                                <img src="[field:picname/]" alt="[field:title/]"
                                    title="[field:title/]" /></a></dt>
                            <dd>
                                <a target="_blank" href="[field:arcurl/]"
                                    title="[field:title/]">
                                    [field:title/]</a></span>
                        </dl>