<li><a href="[field:arcurl/]" title="[field:title/]">
                                <img class="classname" style="display: inline;" src="[field:picname/]"
                                    alt="[field:title/]" title="[field:title/]" /></a> <span><a href="[field:arcurl/]"
                                        title="[field:title/]">
                                        [field:title/]</a></span> </li>