<?php
$z[0]=Array("global","if(@me=2)@me=\"class=mid\";else @me=\"\";",4,98);
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",130,145);
$z[2]=Array("title","",179,193);
$z[3]=Array("picname","",275,291);
$z[4]=Array("title","",327,341);
$z[5]=Array("title","",350,364);
$z[6]=Array("title","",442,456);
$z[7]=Array("arcurl","",465,480);
$z[8]=Array("title","",516,530);
$z[9]=Array("info","",581,594);
$z[10]=Array("arcurl","",633,648);
$z[11]=Array("title","",753,767);
$z[12]=Array("title","",776,790);

?>