<li [field:global name=autoindex runphp="yes"]if(@me=2)@me="class=mid";else @me="";[/field:global]>
					<a class="pic_lk" href="[field:arcurl/]"
                        title="[field:title/]">
                        <img class="classname" style="display: inline;" _src="[field:picname/]"
                            alt="[field:title/]" title="[field:title/]" /></a>
                        <h5>
                            <a title="[field:title/]"  href="[field:arcurl/]">
                                [field:title/]</a><span></span></h5>
                        <p>[field:info/]</p>
                        <a href="[field:arcurl/]" class="s_check">
                            <img src="/Skins/Default/Img/Index/sight_check.gif" alt="[field:title/]" title="[field:title/]" /></a>
                    </li>