<?php
$z[0]=Array("field","",13,34);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",60,82);
$z[1][4]['name']="typename";
$z[2]=Array("field","",84,106);
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n                        <a class=\"xialajia\" title=\"[field:typename/]\" href=\"[field:typedir function=\"cn_substr(@me,200,9) \" /]\">[field:typename/]</a>\r\n						 ",303,544);
$z[3][4]['sql']="Select * from ry_arctype where reid=~id~ ORDER BY id";

?>