<?php
$z[0]=Array("field","",30,51);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",61,83);
$z[1][4]['name']="typename";
$z[2]=Array("field","",86,108);
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n	   <li><a href=\"[field:typedir function=\"cn_substr(@me,200,9) \" /]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n	    ",133,344);
$z[3][4]['sql']="Select * from ry_arctype where reid=~id~ ORDER BY id";

?>