<dl class="pd_list_dl">
                                <dt><a title="[field:title/]" target="_blank" href="[field:arcurl/]">
                                    <img title="[field:title/]" alt="[field:title/]" src="[field:picname/]"></a></dt>
                                <dd><a target="_blank" title="[field:title/]" href="[field:arcurl/]">[field:title/]</a></dd>
                            </dl>