<?php
$z[0]=Array("field","",35,56);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",106,128);
$z[1][4]['name']="typename";
$z[2]=Array("field","",156,178);
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n                            <li ><a href=\"[field:typedir function=\"cn_substr(@me,200,9) \" /]\" target=\"_blank\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n                            ",235,510);
$z[3][4]['sql']="Select * from ry_arctype where reid=~id~ ORDER BY id";

?>