<?php
$z[0]=Array("flink","[field:link/]|",412,473);
$z[0][4]['linktype']="2";
$z[0][4]['row']="20";
$z[1]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\" style=\"padding:0px 8px;margin:0px;\">[field:typename/]</a>",777,936);
$z[1][4]['type']="top";
$z[1][4]['row']="8";
$z[2]=Array("global","",1333,1359);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",1396,1420);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",1456,1477);
$z[4][4]['name']="rexian";
$z[5]=Array("global","",1489,1507);
$z[5][4]['name']="tel";
$z[6]=Array("global","",1544,1562);
$z[6][4]['name']="fax";
$z[7]=Array("global","",1598,1616);
$z[7][4]['name']="add";

?>