<?php
$z[0]=Array("global","<br />\r\n                    {dede:global.tel",1309,1375);
$z[0][4]['name']="rexian";
$z[1]=Array("global","",1379,1399);
$z[1][4]['name']="phone";
$z[2]=Array("channelartlist"," \r\n		 \r\n            <li><a href=\"{dede:field.typeurl/}\"\r\n                title=\"{dede:field.typename/}\">{dede:field.typename/}</a>\r\n               <span style=\"z-index: 999; top:47px; left:1px;display: none;position: absolute;background: none repeat scroll 0 0 #023054;width: 131px;\" class=\"xiala\">\r\n                       {dede:sql sql='Select * from ry_arctype where reid=~id~ ORDER BY id'} \r\n                        <a class=\"xialajia\" title=\"[field:typename/]\" href=\"[field:typedir function=\"cn_substr(@me,200,9) \" /]\">[field:typename/]</a>\r\n						 {/dede:sql}\r\n                    </span>\r\n                </li>\r\n            ",1660,2361);
$z[2][4]['row']="10";
$z[2][4]['typeid']="1,2,8,3,6";
$z[3]=Array("global","",2723,2748);
$z[3][4]['name']="cfg_cmsurl";

?>