<?php
$z[0]=Array("field","",268,287);
$z[0][4]['name']="title";
$z[1]=Array("field","",328,357);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",397,455);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",880,915);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",1338,1360);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n                            <dl class=\"news_dl\">\r\n                                <dt><a class=\"dt_1\" title=\"[field:title/]\" target=\"_blank\" href=\"[field:arcurl/]\">\r\n                                    [field:title/]</a><span class=\"dt_2\">[\r\n                                        [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]\r\n                                        ]</span></dt>\r\n                                <dd>\r\n                                  [field:info/]</dd>\r\n                            </dl>\r\n                             ",1620,2201);
$z[5][4]['pagesize']="15";
$z[6]=Array("pagelist","",2490,2556);
$z[6][4]['listsize']="3";
$z[6][4]['listitem']="index pre pageno next end";
$z[7]=Array("arclist","\r\n                            <dl class=\"pd_list_dl\">\r\n                                <dt><a title=\"[field:title/]\" target=\"_blank\" href=\"[field:arcurl/]\">\r\n                                    <img title=\"[field:title/]\" alt=\"[field:title/]\" src=\"[field:picname/]\"></a></dt>\r\n                                <dd><a target=\"_blank\" title=\"[field:title/]\" href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n                            </dl>\r\n                        ",2920,3439);
$z[7][4]['typeid']="2";
$z[7][4]['flag']="c";
$z[7][4]['row']="3";
$z[8]=Array("include","",3660,3696);
$z[8][4]['filename']="right.htm";
$z[9]=Array("include","",3815,3852);
$z[9][4]['filename']="footer.htm";

?>