<?php
$z[0]=Array("field","",268,287);
$z[0][4]['name']="title";
$z[1]=Array("field","",328,357);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",397,455);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",880,915);
$z[3][4]['filename']="head.htm";
$z[4]=Array("field","",1335,1364);
$z[4][4]['name']="position";
$z[5]=Array("list","\r\n                        <dl class=\"pd_list_dl\">\r\n                            <dt><a target=\"_blank\" href=\"[field:arcurl/]\"\r\n                                title=\"[field:picname/]\">\r\n                                <img src=\"[field:picname/]\" alt=\"[field:title/]\"\r\n                                    title=\"[field:title/]\" /></a></dt>\r\n                            <dd>\r\n                                <a target=\"_blank\" href=\"[field:arcurl/]\"\r\n                                    title=\"[field:title/]\">\r\n                                    [field:title/]</a></span>\r\n                        </dl>\r\n                    ",1574,2234);
$z[5][4]['pagesize']="12";
$z[6]=Array("pagelist","",2650,2716);
$z[6][4]['listsize']="3";
$z[6][4]['listitem']="index pre pageno next end";
$z[7]=Array("arclist","\r\n                                <li><span class=\"fr\">\r\n                                     [field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a target=\"_blank\"\r\n                                        href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                                        [field:title/]</a></li>\r\n                            ",3057,3455);
$z[7][4]['typeid']="3";
$z[7][4]['row']="16";
$z[8]=Array("include","",3715,3751);
$z[8][4]['filename']="right.htm";
$z[9]=Array("include","",3870,3907);
$z[9][4]['filename']="footer.htm";

?>